[Feature] Scripting
BTechTeamRed/GameEngine pull request #18
Opened 2022-10-07 19:17 UTC by Snow106

- Added Script Component. This Component needs to be added to an Entity, and then it needs to Bind with a ScriptableBehavior derived class.
- Added SciptableBehavior. Works similarly to Monobahvior in unity, though a lot less robust.
- Added missing dll exports/imports in Scene.

I was planning on creating a custom script but since we're missing Input I couldn't think of a script I could add that would actually be useful in the long run of the engine. Ideally I was going to make some camera controls for Camera or something like that.

2022-10-07 19:44 UTC, KevinAlexV submitted a review, later dismissed
Looks good to me - comments are great! 

Might be good to have a set of instructions on how to create scripts somewhere (we have your screenshot, but it will likely get buried at some point).

2022-10-07 21:25 UTC, Snow106 commented
> !

I mentioned it in the description of the PR but my idea was to make a custom script to do something... but because we don't have input setup yet I couldn't think of anything that would stay in the engine long term. Open to ideas

2022-10-08 05:01 UTC, roughleythomas requested changes

2022-10-08 05:01 UTC, roughleythomas commented on Engine/src/Engine/Components.h
> +		//Links the Script Component to a scpefic ScriptableBehavior
spelling: specific

2022-10-08 05:01 UTC, roughleythomas commented on Engine/src/Engine/Scripts/ScriptableBehavior.h
> +		virtual void onUpdate(DeltaTime dt) {}
const DeltaTime& ?

2022-10-08 05:01 UTC, roughleythomas commented on Engine/src/Engine/Scripts/ScriptableBehavior.h
> +		virtual void onLateUpdate(DeltaTime dt) {}
const DeltaTime& ?

2022-10-08 05:38 UTC, roughleythomas approved these changes

2022-10-08 05:38 UTC, KevinAlexV approved these changes
In regards to your comment, I completely forgot about an input system, and if a team isn't already working on it, we should get some folks to take a look at that. Some way to read input, and a way to update components with the most recent input (or something that allows us to send input to functions that need to read the most recent input). 

Guess that's for our next meeting, if we're all booked.

2022-10-08 05:38 UTC, merged