Sprite rendering
BTechTeamRed/GameEngine pull request #21
Opened 2022-10-14 09:41 UTC by KevinAlexV

Finalized Sprite Rendering. 

Todo: 
- Adjust screen scaling so sprites scale with window size, and the canvas is not just increased. 

- Create new class to contain GLuint IDs for VBO, IBO, and VAOs of commonly used objects (in this case, sprites). This would allow us to only load them once, and not each time we create a sprite (don't have to redefine verts and such)

Let me know if something needs more explaining, or if any adjustments are necessary!

2022-10-14 09:58 UTC, Snow106 commented
Please add the TODOs to trello if you haven't already.

2022-10-14 09:59 UTC, Snow106 commented
I would suggest renaming Bluedemise2.png to something more descriptive, like bluedemise_splash or bluedemise_text or whatever we use the text version for

2022-10-14 11:09 UTC, Snow106 requested changes

2022-10-14 11:09 UTC, Snow106 commented on Game/Data/Shaders/Fill.vs
> +//layout (location = 2) in vec2 aTexCoord;
can we get rid of commented code if it's not explaining anything?

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/Entity.h
> +		//A template for adding components to an entity.
Not requestion a change just providing my opinion:
All of these functions are named well enough that they're descriptive without the need for a comment. These comments feel redundant

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.cpp
> +#define STB_IMAGE_IMPLEMENTATION
we probably want a guard here

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.h
> +			//Deconstructor
typo: destructor

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.h
>  			std::string m_jsonFileExt = "json";
I know this wasn't put in this PR but guidelines do say to initialize objects with {} instead of = when possible, I personally forgot about that guideline before. Might want to refactor other initializations in this file.

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.h
> +#include "GLFW/glfw3.h"
glad and glfw3 types can be forward declared

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.cpp
> +	void ResourceManager::setIcon(GLFWwindow& window)
Method name feels misleading. You might expect to set the icon for a given entity or object, but it only sets the icon for the application window. (I know it specifically requests a window parameter, but it could still be misinterpreted).
Maybe rename to setApplicationIcon

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.cpp
> +		//std::lock_guard<std::mutex> lock(m_functionLock);
should this be commented out?

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.cpp
> +	GLuint ResourceManager::getTexture(const std::string& Name)
guidelines: param variable should be lower case

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.cpp
>  	nlohmann::json ResourceManager::getJsonData(const std::string& Name)
guidelines: param variable should be lower case

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.cpp
> +		std::unordered_map<std::string, GLuint>::iterator it = m_textures.find(Name);
I'm not sure if I understand why an iterator is needed in a hashmap. Could we instead check if `m_texture.contains(Name)` and continue from there?

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.cpp
> +			if (img.numComponents == 3)
could we use the enum here instead of having 3/4? (magic variables)

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.cpp
> +	ResourceManager::ImageData ResourceManager::readImageData(const std::string& Name)
style guidelines: parameter should be lowecased

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.cpp
> +		std::unordered_map<std::string, std::string>::iterator imagePath = m_filePaths.find(Name);
iterator feels a bit weird to find specific data, though I might be misunderstanding these methods

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.h
> +			#pragma region Constructors & Deconstructors
typo: destructors

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/Scene.h
> +        bool createdVBO = false;
guidelines: initialize values with {}

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/Scene.h
> +        #pragma region OpenGL Scene Management
Side note but did we confirm #pragma regions work in other IDEs?

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/Scene.cpp
> +		//Get entities that contain transform & vertices & color components,
These comments feel to redundant. getEntities is already descriptive enough, we should trust our engineers to understand what these assignments are saying.

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/Scene.cpp
> +			glBindTexture(GL_TEXTURE_2D, texture.texID);
Really cool how you made this work! You made texture loading really efficient 😎

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/Scene.cpp
> +			GLuint colorUniformID = glGetUniformLocation(m_programId, "col");
I think since you made updateMVP, it would be valuable to make a similar function here for color. That should avoid code repetition here with the above for loop

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/Scene.cpp
> +		for (auto [entity, transform, vertices, color] : solidObj.each())
just a suggestion, but I think for clarity you could define solidObj and spirtes each above their respective for loop. Tat should make it clearer what each view's intended use is.

2022-10-14 11:09 UTC, Snow106 commented on Engine/src/Engine/Scene.cpp
> +		vc.vaoID = getSpriteVAO();
this looks much neater now. gj!

2022-10-14 11:43 UTC, KevinAlexV commented on Engine/src/Engine/Scene.cpp
> +		//Get entities that contain transform & vertices & color components,
Honestly, these comments are more for me than anything. My brain registers the green text relatively easily, so I use it as a way to guide myself along chunks of code.
Despite them being redundant, I don't see much of a downside in keeping them. Just for me at the very least

2022-10-14 11:43 UTC, KevinAlexV commented on Engine/src/Engine/Scene.h
> +        #pragma region OpenGL Scene Management
No we haven't. That's perhaps a @ReleaseTheSpice question, as I recall him mentioning using a different IDE. Might be misremembering though

2022-10-14 11:54 UTC, KevinAlexV commented on Engine/src/Engine/ResourceManager.cpp
> +		std::unordered_map<std::string, std::string>::iterator imagePath = m_filePaths.find(Name);
The main reason for the iterator is to ensure it's a valid variable. I tried a few different ways to error check (ensure it's not null), and this seemed to be the best solution. I'm open to suggestions

2022-10-14 12:23 UTC, KevinAlexV commented on Engine/src/Engine/ResourceManager.cpp
> +		std::unordered_map<std::string, GLuint>::iterator it = m_textures.find(Name);
Contains doesn't exist on hashmaps

2022-10-14 12:24 UTC, KevinAlexV commented on Engine/src/Engine/ResourceManager.cpp
> +		//std::lock_guard<std::mutex> lock(m_functionLock);
This was something for @roughleythomas to look at. I left it there since I'm not sure how we needed to lock it. Mind commenting Thomas?

2022-10-14 12:28 UTC, KevinAlexV commented on Engine/src/Engine/ResourceManager.h
> +#include "GLFW/glfw3.h"
Sorry, I'm not too sure how to go about that. Maybe I'm not remembering what forward declaration is.

2022-10-14 12:30 UTC, KevinAlexV commented on Engine/src/Engine/ResourceManager.cpp
> +#define STB_IMAGE_IMPLEMENTATION
A guard..?

2022-10-14 12:30 UTC, KevinAlexV commented on Engine/src/Engine/Entity.h
> +		//A template for adding components to an entity.
See other thread

2022-10-14 12:33 UTC, KevinAlexV commented on Engine/src/Engine/ResourceManager.cpp
> +			if (img.numComponents == 3)
Can we use an Enum for ints? At the very least I'll create an int for this comparison.

2022-10-14 19:56 UTC, Snow106 commented on Engine/src/Engine/ResourceManager.cpp
> +		std::unordered_map<std::string, std::string>::iterator imagePath = m_filePaths.find(Name);
ah .contains seems to be a c++20 method. My bad here then, all good

2022-10-18 01:52 UTC, Snow106 approved these changes, later dismissed

2022-10-18 20:02 UTC, roughleythomas requested changes

2022-10-18 20:02 UTC, roughleythomas commented on Engine/src/Engine/Components.h
>  		CameraComponent(float f, glm::mat4 proj, glm::vec2 view, float fZ, float nZ)
Please make input variable names clearer

2022-10-19 00:53 UTC, KevinAlexV commented on Engine/src/Engine/Components.h
>  		CameraComponent(float f, glm::mat4 proj, glm::vec2 view, float fZ, float nZ)
What specifically should be changed? I didn't write this code, so I'm not too sure what should be altered. @Snow106 @Hevano

2022-10-19 08:17 UTC, KevinAlexV commented on Engine/src/Engine/Components.h
>  		CameraComponent(float f, glm::mat4 proj, glm::vec2 view, float fZ, float nZ)
Ok, I updated this to the best of my knowledge. I'll add a trello ticket to determine a component standard that we can look at later for updating all this.

2022-10-19 20:36 UTC, roughleythomas approved these changes

2022-10-19 20:37 UTC, Snow106 approved these changes

2022-10-19 20:38 UTC, merged