Linking GLFW
BTechTeamRed/GameEngine pull request #4
Opened 2022-09-16 17:12 UTC by mikesinclair66

The cmake build will now link glfw to the project.

2022-09-16 17:29 UTC, Snow106 requested changes

2022-09-16 17:29 UTC, Snow106 commented on CMakeLists.txt
> +add_subdirectory(${PROJECT_SOURCE_DIR}/thirdparty/glfw)
should be add_subdirectory(${PROJECT_SOURCE_DIR}/thirdparty/glfw3)

2022-09-16 18:16 UTC, Snow106 approved these changes

2022-09-17 04:38 UTC, ReleaseTheSpice approved these changes

2022-09-17 04:39 UTC, merged