Added Style Guidelines to readme
BTechTeamRed/GameEngine pull request #5
Opened 2022-09-17 06:00 UTC by Snow106

2022-09-17 19:40 UTC, mikesinclair66 requested changes
These r great guidelines, but I think we should have a discussion between the team as to which ones majority agrees upon.

2022-09-20 21:25 UTC, ReleaseTheSpice approved these changes, later dismissed

2022-09-21 03:27 UTC, ReleaseTheSpice approved these changes

2022-09-22 21:09 UTC, mikesinclair66 approved these changes

2022-09-22 21:41 UTC, merged