Fixed scene swapping
BTechTeamRed/GameEngine pull request #67
Opened 2022-12-01 06:43 UTC by ReleaseTheSpice

2022-12-01 06:45 UTC, JackyLau01 approved these changes, later dismissed

2022-12-01 06:51 UTC, Snow106 requested changes

2022-12-01 06:51 UTC, Snow106 commented on Engine/src/Engine/SceneBuilder/Scene.cpp
> +			if (score > 5) {
brackets

2022-12-01 06:51 UTC, Snow106 commented on Engine/src/Engine/SceneBuilder/Scene.cpp
> +		int count = 0;
we can get rid of this

2022-12-01 06:51 UTC, Snow106 commented on Engine/src/Engine/SceneBuilder/Scene.cpp
> +		glm::vec3 dimensions;
let's make this into a method since it's called in two places

2022-12-01 07:19 UTC, roughleythomas submitted a review, later dismissed

2022-12-01 08:13 UTC, Snow106 approved these changes, later dismissed

2022-12-03 05:58 UTC, Snow106 approved these changes

2022-12-03 06:13 UTC, roughleythomas approved these changes

2022-12-03 06:13 UTC, merged